/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#0b1c30",
        "on-secondary-fixed": "#0d1c2f",
        "on-surface-variant": "#45464d",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#d3e4fe",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b9c7e0",
        "primary-container": "#131b2e",
        "primary-fixed": "#dae2fd",
        "on-tertiary-container": "#75859d",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "on-background": "#191c1e",
        tertiary: "#000000",
        "inverse-on-surface": "#eff1f3",
        background: "#f7f9fb",
        secondary: "#515f74",
        "surface-tint": "#565e74",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed-variant": "#3a485c",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#7c839b",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#57657b",
        "secondary-fixed": "#d5e3fd",
        primary: "#000000",
        "on-surface": "#191c1e",
        "on-primary-fixed": "#131b2e",
        "outline-variant": "#c6c6cd",
        surface: "#f7f9fb",
        "on-primary-fixed-variant": "#3f465c",
        "surface-variant": "#e0e3e5",
        outline: "#76777d",
        "on-tertiary-fixed-variant": "#38485d",
        "inverse-primary": "#bec6e0",
        "secondary-container": "#d5e3fd",
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        base: "4px",
        lg: "24px",
        xs: "8px",
        sm: "12px",
        margin: "40px",
        gutter: "24px",
        xl: "32px",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      animation: {
        "pulse-slow": "pulse 2s cubic-bezier(0.4,0,0.6,1) infinite",
        "slide-in": "slideIn 0.4s ease both",
        "fade-up": "fadeUp 0.5s ease both",
      },
      keyframes: {
        slideIn: {
          from: { opacity: "0", transform: "translateY(-10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeUp: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
